# Generated by Django 4.1.6 on 2023-03-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invoice_paywithcredit_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoiceNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
