# Generated by Django 4.1.6 on 2023-02-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
    ]
